// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['connections']['ConnectionManager']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['connections']['ConnectionManager']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['connections']['ConnectionManager']['DisconnectAll']();
}

export function GetClient(arg1) {
  return window['go']['connections']['ConnectionManager']['GetClient'](arg1);
}

export function GetConnectedClientIDs() {
  return window['go']['connections']['ConnectionManager']['GetConnectedClientIDs']();
}

export function Init(arg1) {
  return window['go']['connections']['ConnectionManager']['Init'](arg1);
}
