// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';
import {context} from '../models';

export function Connect(arg1:number):Promise<boolean|string>;

export function Disconnect(arg1:number):Promise<boolean|string>;

export function DisconnectAll():Promise<boolean|string>;

export function GetClient(arg1:number):Promise<connections.ActiveConnection>;

export function GetConnectedClientIDs():Promise<Array<number>>;

export function Init(arg1:context.Context):Promise<void>;
