export const mongoMethods = [
  { label: 'find', detail: '(filter?, projection?) - Query documents', snippet: 'find({$1})$0' },
  { label: 'findOne', detail: '(filter?) - Find a single document', snippet: 'findOne({$1})$0' },
  { label: 'insertOne', detail: '(document) - Insert a document', snippet: 'insertOne({$1})$0' },
  { label: 'insertMany', detail: '(documents) - Insert multiple documents', snippet: 'insertMany([$1])$0' },
  { label: 'updateOne', detail: '(filter, update) - Update a document', snippet: 'updateOne({$1}, {$2})$0' },
  { label: 'updateMany', detail: '(filter, update) - Update multiple documents', snippet: 'updateMany({$1}, {$2})$0' },
  { label: 'deleteOne', detail: '(filter) - Delete a document', snippet: 'deleteOne({$1})$0' },
  { label: 'deleteMany', detail: '(filter) - Delete multiple documents', snippet: 'deleteMany({$1})$0' },
  { label: 'replaceOne', detail: '(filter, replacement) - Replace a document', snippet: 'replaceOne({$1}, {$2})$0' },
  { label: 'countDocuments', detail: '(filter?) - Count matching documents', snippet: 'countDocuments({$1})$0' },
  { label: 'aggregate', detail: '(pipeline) - Run aggregation pipeline', snippet: 'aggregate([$1])$0' },
]

export const queryOperators = [
  { label: '$eq', detail: 'Matches values equal to a value' },
  { label: '$ne', detail: 'Matches values not equal to a value' },
  { label: '$gt', detail: 'Matches values greater than a value' },
  { label: '$gte', detail: 'Matches values greater than or equal to a value' },
  { label: '$lt', detail: 'Matches values less than a value' },
  { label: '$lte', detail: 'Matches values less than or equal to a value' },
  { label: '$in', detail: 'Matches any value in an array' },
  { label: '$nin', detail: 'Matches none of the values in an array' },
  { label: '$exists', detail: 'Matches documents with the field' },
  { label: '$type', detail: 'Matches documents by BSON type' },
  { label: '$regex', detail: 'Matches by regular expression' },
  { label: '$not', detail: 'Inverts a query expression' },
  { label: '$and', detail: 'Joins clauses with logical AND' },
  { label: '$or', detail: 'Joins clauses with logical OR' },
  { label: '$nor', detail: 'Joins clauses with logical NOR' },
  { label: '$elemMatch', detail: 'Matches array elements' },
  { label: '$size', detail: 'Matches arrays by size' },
  { label: '$all', detail: 'Matches arrays containing all elements' },
]

export const cursorMethods = [
  { label: 'limit', detail: '(n) - Limit number of results' },
  { label: 'skip', detail: '(n) - Skip first n results' },
  { label: 'sort', detail: '(sortSpec) - Sort results, e.g. { field: 1 }' },
]

export const aggStages = [
  { label: '$match', detail: 'Filter documents' },
  { label: '$group', detail: 'Group documents by expression' },
  { label: '$project', detail: 'Reshape documents' },
  { label: '$sort', detail: 'Sort documents' },
  { label: '$limit', detail: 'Limit number of documents' },
  { label: '$skip', detail: 'Skip documents' },
  { label: '$unwind', detail: 'Deconstruct array field' },
  { label: '$lookup', detail: 'Join with another collection' },
  { label: '$addFields', detail: 'Add new fields' },
  { label: '$set', detail: 'Add or overwrite fields' },
  { label: '$unset', detail: 'Remove fields' },
  { label: '$replaceRoot', detail: 'Replace root document' },
  { label: '$count', detail: 'Count documents' },
  { label: '$out', detail: 'Write results to collection' },
  { label: '$merge', detail: 'Merge results into collection' },
  { label: '$facet', detail: 'Multiple aggregation pipelines' },
  { label: '$bucket', detail: 'Categorize into buckets' },
  { label: '$sample', detail: 'Randomly select documents' },
]
