// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common} from '../models';
import {context} from '../models';

export function CreateFolder(arg1:string,arg2:number):Promise<common.EmptyResult>;

export function GetRegisteredServers():Promise<common.Result___vervet_internal_configuration_RegisteredServer_>;

export function Init(arg1:context.Context):Promise<void>;

export function RemoveNode(arg1:number,arg2:boolean):Promise<common.EmptyResult>;

export function SaveRegisterServer(arg1:string,arg2:number,arg3:string):Promise<common.EmptyResult>;
