// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CreateCollection(arg1:string,arg2:string,arg3:string):Promise<api.EmptyResult>;

export function DropCollection(arg1:string,arg2:string,arg3:string):Promise<api.EmptyResult>;

export function GetCollectionSchema(arg1:string,arg2:string,arg3:string):Promise<api.Result_vervet_internal_models_CollectionSchema_>;

export function GetCollections(arg1:string,arg2:string):Promise<api.Result___string_>;

export function GetDatabaseStatistics(arg1:string,arg2:string):Promise<api.Result_map_string_interface____>;

export function GetServerStatistics(arg1:string):Promise<api.Result_map_string_interface____>;

export function GetStatistics(arg1:string,arg2:string,arg3:string):Promise<api.Result_map_string_interface____>;

export function GetViews(arg1:string,arg2:string):Promise<api.Result___string_>;

export function RenameCollection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.EmptyResult>;
