// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2, arg3) {
  return window['go']['api']['CollectionsProxy']['CreateCollection'](arg1, arg2, arg3);
}

export function DropCollection(arg1, arg2, arg3) {
  return window['go']['api']['CollectionsProxy']['DropCollection'](arg1, arg2, arg3);
}

export function GetCollectionSchema(arg1, arg2, arg3) {
  return window['go']['api']['CollectionsProxy']['GetCollectionSchema'](arg1, arg2, arg3);
}

export function GetCollections(arg1, arg2) {
  return window['go']['api']['CollectionsProxy']['GetCollections'](arg1, arg2);
}

export function GetDatabaseStatistics(arg1, arg2) {
  return window['go']['api']['CollectionsProxy']['GetDatabaseStatistics'](arg1, arg2);
}

export function GetServerStatistics(arg1) {
  return window['go']['api']['CollectionsProxy']['GetServerStatistics'](arg1);
}

export function GetStatistics(arg1, arg2, arg3) {
  return window['go']['api']['CollectionsProxy']['GetStatistics'](arg1, arg2, arg3);
}

export function GetViews(arg1, arg2) {
  return window['go']['api']['CollectionsProxy']['GetViews'](arg1, arg2);
}

export function RenameCollection(arg1, arg2, arg3, arg4) {
  return window['go']['api']['CollectionsProxy']['RenameCollection'](arg1, arg2, arg3, arg4);
}
