// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetDatabaseStatistics(arg1:string,arg2:string):Promise<api.Result_map_string_interface____>;

export function GetStatistics(arg1:string,arg2:string,arg3:string):Promise<api.Result_map_string_interface____>;
