// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['api']['ConnectionsProxy']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['api']['ConnectionsProxy']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['api']['ConnectionsProxy']['DisconnectAll']();
}

export function GetCollections(arg1, arg2) {
  return window['go']['api']['ConnectionsProxy']['GetCollections'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['api']['ConnectionsProxy']['GetConnections']();
}

export function GetDatabases(arg1) {
  return window['go']['api']['ConnectionsProxy']['GetDatabases'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['api']['ConnectionsProxy']['TestConnection'](arg1);
}
