// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CancelQuery(arg1:string):Promise<api.EmptyResult>;

export function CheckMongosh():Promise<api.Result_bool_>;

export function Connect(arg1:string):Promise<api.Result_vervet_internal_models_Connection_>;

export function Disconnect(arg1:string):Promise<api.EmptyResult>;

export function DisconnectAll():Promise<api.EmptyResult>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<api.Result_string_>;

export function GetCollections(arg1:string,arg2:string):Promise<api.Result___string_>;

export function GetConnections():Promise<api.Result___vervet_internal_models_Connection_>;

export function GetDatabases(arg1:string):Promise<api.Result___string_>;

export function GetViews(arg1:string,arg2:string):Promise<api.Result___string_>;

export function TestConnection(arg1:string):Promise<api.EmptyResult>;
