// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function Connect(arg1:number):Promise<api.EmptyResult>;

export function Disconnect(arg1:number):Promise<api.EmptyResult>;

export function DisconnectAll():Promise<api.EmptyResult>;

export function GetConnectionIDs():Promise<api.Result___int_>;
