// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['api']['ConnectionsProxy']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['api']['ConnectionsProxy']['Disconnect'](arg1);
}

export function DisconnectAll() {
  return window['go']['api']['ConnectionsProxy']['DisconnectAll']();
}

export function GetConnectionIDs() {
  return window['go']['api']['ConnectionsProxy']['GetConnectionIDs']();
}

export function GetDatabases(arg1) {
  return window['go']['api']['ConnectionsProxy']['GetDatabases'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['api']['ConnectionsProxy']['TestConnection'](arg1);
}
