// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function DropDatabase(arg1:string,arg2:string):Promise<api.EmptyResult>;

export function GetDatabaseStatistics(arg1:string,arg2:string):Promise<api.Result_map_string_interface____>;

export function GetDatabases(arg1:string):Promise<api.Result___string_>;
