// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DropDatabase(arg1, arg2) {
  return window['go']['api']['DatabasesProxy']['DropDatabase'](arg1, arg2);
}

export function GetDatabaseStatistics(arg1, arg2) {
  return window['go']['api']['DatabasesProxy']['GetDatabaseStatistics'](arg1, arg2);
}

export function GetDatabases(arg1) {
  return window['go']['api']['DatabasesProxy']['GetDatabases'](arg1);
}
