// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFile(arg1) {
  return window['go']['api']['FilesProxy']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['api']['FilesProxy']['SaveFile'](arg1, arg2, arg3);
}

export function SelectFile(arg1, arg2) {
  return window['go']['api']['FilesProxy']['SelectFile'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['api']['FilesProxy']['WriteFile'](arg1, arg2);
}
