// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['api']['IndexesProxy']['CreateIndex'](arg1, arg2, arg3, arg4);
}

export function DropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['api']['IndexesProxy']['DropIndex'](arg1, arg2, arg3, arg4);
}

export function EditIndex(arg1, arg2, arg3, arg4) {
  return window['go']['api']['IndexesProxy']['EditIndex'](arg1, arg2, arg3, arg4);
}

export function GetIndexes(arg1, arg2, arg3) {
  return window['go']['api']['IndexesProxy']['GetIndexes'](arg1, arg2, arg3);
}
