// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {api} from '../models';

export function CreateIndex(arg1:string,arg2:string,arg3:string,arg4:models.CreateIndexRequest):Promise<api.EmptyResult>;

export function DropIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.EmptyResult>;

export function EditIndex(arg1:string,arg2:string,arg3:string,arg4:models.EditIndexRequest):Promise<api.EmptyResult>;

export function GetIndexes(arg1:string,arg2:string,arg3:string):Promise<api.Result___vervet_internal_models_Index_>;
