// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLogin(arg1) {
  return window['go']['api']['OIDCProxy']['CancelLogin'](arg1);
}

export function ResetSession(arg1) {
  return window['go']['api']['OIDCProxy']['ResetSession'](arg1);
}
