// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CancelLogin(arg1:string):Promise<api.EmptyResult>;

export function ResetSession(arg1:string):Promise<api.EmptyResult>;
