// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {models} from '../models';

export function CreateGroup(arg1:string,arg2:string):Promise<api.EmptyResult>;

export function ExportServers(arg1:Array<string>,arg2:boolean):Promise<api.Result_string_>;

export function GetConnectionConfig(arg1:string):Promise<api.Result_vervet_internal_models_ConnectionConfig_>;

export function GetServer(arg1:string):Promise<api.Result_vervet_internal_models_RegisteredServer_>;

export function GetServers():Promise<api.Result___vervet_internal_models_RegisteredServer_>;

export function GetURI(arg1:string):Promise<api.Result_string_>;

export function ImportServers(arg1:string):Promise<api.Result___vervet_internal_models_RegisteredServer_>;

export function RemoveNode(arg1:string):Promise<api.EmptyResult>;

export function SaveServer(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.EmptyResult>;

export function SaveServerWithConfig(arg1:string,arg2:string,arg3:string,arg4:models.ConnectionConfig):Promise<api.EmptyResult>;

export function UpdateGroup(arg1:string,arg2:string,arg3:string):Promise<api.EmptyResult>;

export function UpdateServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<api.EmptyResult>;

export function UpdateServerWithConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:models.ConnectionConfig):Promise<api.EmptyResult>;
