// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {models} from '../models';

export function GetAppVersion():Promise<api.Result_string_>;

export function GetAvailableFonts():Promise<api.Result___vervet_internal_models_Font_>;

export function GetSettings():Promise<api.Result_vervet_internal_models_Settings_>;

export function GetWindowState():Promise<api.Result_vervet_internal_models_WindowState_>;

export function ResetSettings():Promise<api.Result_vervet_internal_models_Settings_>;

export function SaveWindowState(arg1:models.WindowState):Promise<api.EmptyResult>;

export function SetSettings(arg1:models.Settings):Promise<api.EmptyResult>;
