// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['api']['SettingsProxy']['GetAppVersion']();
}

export function GetAvailableFonts() {
  return window['go']['api']['SettingsProxy']['GetAvailableFonts']();
}

export function GetSettings() {
  return window['go']['api']['SettingsProxy']['GetSettings']();
}

export function GetWindowState() {
  return window['go']['api']['SettingsProxy']['GetWindowState']();
}

export function ResetSettings() {
  return window['go']['api']['SettingsProxy']['ResetSettings']();
}

export function SaveWindowState(arg1) {
  return window['go']['api']['SettingsProxy']['SaveWindowState'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['api']['SettingsProxy']['SetSettings'](arg1);
}
