// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function CancelQuery(arg1:string):Promise<api.EmptyResult>;

export function CheckMongosh():Promise<api.Result_bool_>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<api.Result_vervet_internal_models_QueryResult_>;
