// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetOs():Promise<api.Result_vervet_internal_api_OperatingSystem_>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function RevealLogsFolder():Promise<api.EmptyResult>;
