// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOs() {
  return window['go']['api']['SystemProxy']['GetOs']();
}

export function Log(arg1, arg2) {
  return window['go']['api']['SystemProxy']['Log'](arg1, arg2);
}

export function RevealLogsFolder() {
  return window['go']['api']['SystemProxy']['RevealLogsFolder']();
}
