// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOs() {
  return window['go']['api']['SystemProxy']['GetOs']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['api']['SystemProxy']['SaveFile'](arg1, arg2, arg3);
}

export function SelectFile(arg1, arg2) {
  return window['go']['api']['SystemProxy']['SelectFile'](arg1, arg2);
}
