// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function CheckNow():Promise<api.Result_vervet_internal_updates_UpdateInfo_>;

export function DismissUpdate(arg1:string):Promise<api.EmptyResult>;

export function Init(arg1:context.Context):Promise<void>;

export function OpenReleasePage(arg1:string):Promise<api.EmptyResult>;
