// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNow() {
  return window['go']['api']['UpdatesProxy']['CheckNow']();
}

export function DismissUpdate(arg1) {
  return window['go']['api']['UpdatesProxy']['DismissUpdate'](arg1);
}

export function Init(arg1) {
  return window['go']['api']['UpdatesProxy']['Init'](arg1);
}

export function OpenReleasePage(arg1) {
  return window['go']['api']['UpdatesProxy']['OpenReleasePage'](arg1);
}
