// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1) {
  return window['go']['api']['WorkspacesProxy']['AddFolder'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['api']['WorkspacesProxy']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['api']['WorkspacesProxy']['CreateFolder'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['api']['WorkspacesProxy']['CreateWorkspace'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['api']['WorkspacesProxy']['DeleteFile'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['api']['WorkspacesProxy']['DeleteWorkspace'](arg1);
}

export function GetWorkspaces() {
  return window['go']['api']['WorkspacesProxy']['GetWorkspaces']();
}

export function Init(arg1) {
  return window['go']['api']['WorkspacesProxy']['Init'](arg1);
}

export function ReadDirectory(arg1) {
  return window['go']['api']['WorkspacesProxy']['ReadDirectory'](arg1);
}

export function RemoveFolder(arg1, arg2) {
  return window['go']['api']['WorkspacesProxy']['RemoveFolder'](arg1, arg2);
}

export function RenameFile(arg1, arg2) {
  return window['go']['api']['WorkspacesProxy']['RenameFile'](arg1, arg2);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['api']['WorkspacesProxy']['RenameWorkspace'](arg1, arg2);
}

export function SetActiveWorkspace(arg1) {
  return window['go']['api']['WorkspacesProxy']['SetActiveWorkspace'](arg1);
}
