// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function AddFolder(arg1:string):Promise<api.Result_string_>;

export function CreateFile(arg1:string,arg2:string):Promise<api.Result_string_>;

export function CreateFolder(arg1:string,arg2:string):Promise<api.Result_string_>;

export function CreateWorkspace(arg1:string):Promise<api.Result_vervet_internal_models_Workspace_>;

export function DeleteFile(arg1:string):Promise<api.EmptyResult>;

export function DeleteWorkspace(arg1:string):Promise<api.EmptyResult>;

export function GetWorkspaces():Promise<api.Result_vervet_internal_models_WorkspaceData_>;

export function Init(arg1:context.Context):Promise<void>;

export function ReadDirectory(arg1:string):Promise<api.Result___vervet_internal_models_DirectoryEntry_>;

export function RemoveFolder(arg1:string,arg2:string):Promise<api.EmptyResult>;

export function RenameFile(arg1:string,arg2:string):Promise<api.EmptyResult>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<api.EmptyResult>;

export function SetActiveWorkspace(arg1:string):Promise<api.EmptyResult>;
